### PR TITLE
Xcode6.3 tests

### LINKED ISSUE #513: Tests won't compile on Xcode 6.3
It looks as if the Quick and Nimble dependencies need to upgrade to be compatible with the latest changes in swift. In the meantime, I can't seem to be able to compile the tests.

screen shot 2015-05-06 at 11 56 55 am
screen shot 2015-05-06 at 11 59 22 am
screen shot 2015-05-06 at 11 59 28 am

### PR DESCRIPTION
**Pull request by dcaunt**
Fixes #513

### CODE REVIEW

**Comment by dcaunt** [comment]
Looks like Travis [doesn't support Xcode 6.3 yet](http://blog.travis-ci.com/2015-04-20-state-of-the-mac-infrastructure-on-travis-ci/).

**Comment by jspahrsummers** [comment]
Sorry about [the delay](https://twitter.com/jspahrsummers/status/597520138456305665)!

This looks good to go. Can you please remove `.travis.yml` for now, so it stops giving us failed statuses?

**Comment by adamkaplan** [comment]
Hey @dcaunt! Funny bumping in to you here... Could you find some Travis hack that would get this to not appear failed? It's really a PITA to work with master and 6.3 :P

**Comment by dcaunt** [comment]
@jspahrsummers Is the `Build only if .travis.yml is present` setting `ON`?

**Comment by jspahrsummers** [comment]
Sorry, it is now.

Thanks! :sparkles:

**Pull request merged**
