### PR TITLE
fixes libextobjc header collision when using libextobjc

### PR DESCRIPTION
**Pull request by RonanLB**
this pull request relates to the issue reported here:
https://github.com/Mantle/Mantle/pull/610#issuecomment-146945745

Mantle's version of libextobjc would conflict with another libextobjc dependency import while using pods.

In order to maintain Mantle 1.x working with the new cocoapods 0.38+ and version 7.x+ of xcode, those Mantle specific files have been renamed by adding to their name the "MTL" prefix

### CODE REVIEW

**Comment by robb** [comment]
LGTM

**Comment by RonanLB** [comment]
@robb would it be possible to tag the changeset to  1.5.6 ?

**Comment by robb** [comment]
Whoops, forgot about that one.

@dcaunt Can you work your cocoapods magic when you get a moment? :bow:

**Comment by dcaunt** [comment]
I've pushed 1.5.6 – should be live shortly

**Comment by RonanLB** [comment]
Thanks @dcaunt

**Comment by priteshshah1983** [comment]
Thanks guys! Really appreciate all the work!

**Comment by yangtaoNewGame** [comment]
my project must be 7.0+ .  you update to  2.x ，my project can not use 2.x.    oh ,my god.

**Comment by yangtaoNewGame** [comment]
version 1.5.6  ,can my project use it ?.

**Comment by dcaunt** [comment]
Yes, you can use 1.5.6.

**Comment by yangtaoNewGame** [comment]
hi dcaunt , in stackoverflow.  http://stackoverflow.com/questions/32632280/how-to-build-mantle-v2-for-ios-7-0 ,   say " if you still want to user Mantle,either include its files into you project manully or use Cocoapods to build it as a static library using one of existing cocoapods spec file for mantle ".   is it true??

**Comment by dcaunt** [comment]
That's correct. Installation via CocoaPods is not officially supported but the code itself should work all the way back to iOS 5.0.

**Pull request merged**
