### PR TITLE
Update README.md System Requirements section

### PR DESCRIPTION
**Pull request by chipp**
Mantle supports OS X 10.9+ and iOS 8.0+.

### CODE REVIEW

**Comment by dcaunt** [comment]
@jspahrsummers Do you think it would be clearer to say that inclusion as a framework requires 10.9/8.0 but the code itself requires 10.7/5.0? I suspect that the majority of projects using Mantle do not include it as a framework and it would be a shame for those users to drop Mantle or stay on v1 due to a lack of understanding.

**Comment by jspahrsummers** [comment]
I think our documentation should match the deployment target set in the project. Otherwise, we might accidentally break something on a previous version, not catch it with Xcode, and cause even more confusion as a result.

**Comment by liuxuan30** [comment]
What API requires iOS 8.0? It forces me not to use Mantle until iOS 7 goes down to a very small portion.

**Comment by dcaunt** [comment]
@liuxuan30 As discussed, Mantle's code does not require iOS 8, however the project does. If you install Mantle via CocoaPods or include the source in your project manually it will work fine on iOS 7.

**Pull request merged**
