### PR TITLE
Add automatically generated change log file.

### PR DESCRIPTION
**Pull request by skywinder**
Hi, your automatically parse JSON, and this thing automatically parse your GitHub issues! :boom: 

As I can see, you are carefully fill tags and labels for issues in your repo.
I created a [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator), that generate change log file based on tags, issues and merged pull requests (and split them to separate lists according labels) from GitHub issue tracker.
[This Change Log](https://github.com/skywinder/Mantle/blob/add-change-log-file/CHANGELOG.md) was automatically generated by this script.
It helps to easily found what and when was fixed and implemented.
You can easily update this file in future by running script: `github_changelog_generator` in your repo folder.
Hope you find this commit as useful.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Thanks for the suggestion! :sparkles:

I'm generally not a fan of in-repo changelogs, but information like this could make sense with Mantle's Releases. However, usually that information gets manually edited too.

If you add support for that sort of workflow, it might be interesting, but I don't think we want to start including a `CHANGELOG.md`.

**Comment by skywinder** [comment]
Thanks for feedback. Your opinion is very valuable for me.
Can you provide example, what kind of edits you would like to add?

BDW:
This script has some customisation features already:
- it automatically exclude questions and invalid issues from list.
- you can specify, which labels should (or should not) include in change log.
- to mention about some missing feature, that not in change log yet - you can create issue with description of this feature, set milestone to the corresponding for this feature tag. And it will appear in change log with next generation.

**Comment by jspahrsummers** [comment]
> Can you provide example, what kind of edits you would like to add?

Since we wouldn't be using a `CHANGELOG.md`, it would be great to create a changelog of _only_ the new stuff since the last release, and then dump that into the GitHub Release body.

I guess the only other thing is that this seems to include _closed_ pull requests in addition to merged PRs. Can those be omitted somehow?

**Comment by skywinder** [comment]
@jspahrsummers :+1: thanks for quick review! It helps me a lot!

>  it would be great to create a changelog of only the new stuff since the last release, and then dump that into the GitHub Release body.

You can run this script with `--unreleased-only` option:

    github_changelog_generator --unreleased-only Mantle/Mantle

And it generate list with "only the new stuff since the last release"!

> dump that into the GitHub Release body.

I already have a plans to implement this option directly in script: https://github.com/skywinder/Github-Changelog-Generator/issues/56 any suggestions and wishes about implementation details are kindly welcome!

Hope, I can help you to automate your release process as much as possible.

> I guess the only other thing is that this seems to include closed pull requests in addition to merged PRs. Can those be omitted somehow?

Yep! This is a bug. Appears after bunch of refactoring in the last major update. Many thanks for mention it! I create an issue and it already fix it in `1.3.10` https://github.com/skywinder/Github-Changelog-Generator/issues/69

**Comment by jspahrsummers** [comment]
> You can run this script with `--unreleased-only` option

Is there a way to do this between arbitrary commits? I sometimes create tags before writing the release notes, so it'd be nice to create a changelog for “between tag A and tag B.”

**Comment by skywinder** [comment]
Not, yet. But it's easy to implement in next releases. I will let you know. https://github.com/skywinder/github-changelog-generator/issues/172

**Comment by skywinder** [comment]
@jspahrsummers Hi! As I promise - I let you know, that now you can set specific tags, to generate change log between them. 
Use `--between-tags` option to specify tags.

**Comment by jspahrsummers** [comment]
@skywinder Awesome! I'll take another look soon.

**Pull request closed without merging**
