### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by jspahrsummers**
The Next Big Thing™

### CODE REVIEW

**Comment by robb** [comment]
It's happening!

**Comment by jspahrsummers** [comment]
@robb Do you think the 2.0 milestone is complete? Do you know of any other work that needs to happen which isn't captured there?

**Comment by robb** [comment]
I think it's peachy

**Comment by robb** [comment]
@jspahrsummers would you do us the honors and tag a Release Candidate?

**Comment by jspahrsummers** [comment]
[Tagged](https://github.com/Mantle/Mantle/releases/tag/2.0-beta.1), and `2.0-development` is now the default branch as well.

**Pull request merged**
