### PR TITLE
Xcode 10.2 Compatibility

### PR DESCRIPTION
**Pull request by yhkaplan**
Xcode 10.2 deprecates Swift 3, requiring a minimum of Swift 4, so I am updating the project's Swift version to 4.2, and also updating Quick and Nimble to versions that support 4.2.

### CODE REVIEW

**Comment by dcaunt** [comment]
Thanks for opening a PR ✨ ! Looks like the macOS and tvOS builds are failing on Travis?

**Comment by yhkaplan** [comment]
Took me a few tries, but I solved the issues (destination format and minimum versions for Swift and OSs).

**Comment by yhkaplan** [comment]
@dcaunt Sorry to bother you, but when do you think you’ll get a chance to look?

**Comment by yhkaplan** [comment]
@jspahrsummers @dcaunt Do you think you'll be able to take a look soon?

**Pull request closed without merging**
