### PR TITLE
Add support for dots in key paths using literals

### LINKED ISSUE #508: Parsing JSON with Period in Key
I am trying to parse some JSON with a period in it, but it is causing issues with Mantle. Any way of working around this issue without modifying the keys before Mantle sees them?

Example: 

``` json
    "optional.detail" : {
      "name" : "Test",
      "all.pictures" : [
        {
          "original" : "original.jpg",
          "mobile" : "mobile.jpg"
        }
      ]
    }
```

### LINKED ISSUE #769: JSONKeyPath with . returns nil
in NSDictionary+MTLJSONKeyPath.m

      - (id)mtl_valueForJSONKeyPath:(NSString *)JSONKeyPath success:(BOOL *)success error:(NSError **)error {
	NSArray *components = [JSONKeyPath componentsSeparatedByString:@"."];

	id result = self;
	for (NSString *component in components) {
		// Check the result before resolving the key path component to not
		// affect the last value of the path.
		if (result == nil || result == NSNull.null) break;

		if (![result isKindOfClass:NSDictionary.class]) {
			if (error != NULL) {
				NSDictionary *userInfo = @{
					NSLocalizedDescriptionKey: NSLocalizedString(@"Invalid JSON dictionary", @""),
					NSLocalizedFailureReasonErrorKey: [NSString stringWithFormat:NSLocalizedString(@"JSON key path %1$@ could not resolved because an incompatible JSON dictionary was supplied: \"%2$@\"", @""), JSONKeyPath, self]
				};

				*error = [NSError errorWithDomain:MTLJSONAdapterErrorDomain code:MTLJSONAdapterErrorInvalidJSONDictionary userInfo:userInfo];
			}

			if (success != NULL) *success = NO;

			return nil;
		}

		result = result[component];
	}

	if (success != NULL) *success = YES;

	return result;
    }

all JSONKeyPath with <.> will be separated.
my problem is, i have keys from the json like
`
"sticker.name" : "sample name"
`
 and result[component] will always return nil

How do i work with this case? Thanks!

### PR DESCRIPTION
**Pull request by conradev**
I finally came across this issue myself and was motivated enough to fix it! I implemented the suggestion in #508 and wrote a version of #656 for Mantle 2.0.

Let me know what you think, @dcaunt. I am a little unfamiliar with the proper formatting.

Fixes #769 
Fixes #508 
Supercedes #656

### CODE REVIEW

**Comment by wlisac** [comment]
@dcaunt @robb I'd love to see this feature become available. Anything I can do to help get this merged in?

**Comment by robb** [comment]
@abotkin-cpi What's your take on reviving this one or #790?

**Comment by abotkin-cpi** [comment]
@robb Given that users are going to have to learn the syntax anyways ([jq the command line tool has a different scheme for this](https://github.com/stedolan/jq/issues/204#issuecomment-27089261), I'd lean towards the #790 implementation.

**Comment by robb** [comment]
Fair.

**Comment by abotkin-cpi** [comment]
Rebased #790 to master & opened up a new PR: #856

**Pull request closed without merging**
