### PR TITLE
Added watchOS 2 target

### PR DESCRIPTION
**Pull request by AriX**

### CODE REVIEW

**Comment by robb** [comment]
Thanks for the Pull Request 💖

Looks like the build scripts need to be updated not to run the watchOS target until travis ci supports Xocde 7.

**Comment by robb** [comment]
Hi, would you mind resolving the conflicts so we can merge this one? Sorry, I know merging `pbxproj` files is not fun :grimacing:

**Comment by AriX** [comment]
Pushed an updated version - give this a try! (Note: watchOS doesn't currently support testing, so there is no testing target. Anecdotally, I just tested the Mantle Watch target in our Apple Watch app and it worked great for our uses.)

**Comment by conradev** [comment]
@robb, you have more familiarity with the CI system, do you know how the iOS target builds with no codesigning identities? The watchOS build is failing at that check.

**Comment by robb** [comment]
I'm wondering about that myself, I'll try to look into it like Tuesday

**Comment by istx25** [comment]
Unfortunately my attempt at fixing this failed (#727). I researched this some more and think this may be helpful though, @robb: https://github.com/travis-ci/travis-ci/issues/3072.

**Comment by dcaunt** [comment]
Closing this in favour of #730, thanks to all who contributed !

**Pull request closed without merging**
