### PR TITLE
Generate binary framework for Carthage users.

### PR DESCRIPTION
**Pull request by 3a4oT**
- Refactored existing `on push` workflow.

- Added a workflow which verifies that Carthage is able to build Mantle.

- Added a workflow that creates and automatically uploads the Mantle.framework.zip to GitHub releases on a new tag was pushed. (For example, you pushed new tag 2.3 - this step will automatically create GitHub release and attach binary framework to it so Carthage users can pull it instead of building from source).

### CODE REVIEW

**Comment by robb** [comment]
Looks sharp, thanks a lot 💖

**Comment by 3a4oT** [comment]
Thanks! Would you mind to push the new tag so we can verify new workflow and start using attached binary?)

**Comment by robb** [comment]
Hmm, doesn't seem to have worked https://github.com/Mantle/Mantle/actions/runs/267467413.

**Comment by 3a4oT** [comment]
@robb Yeah should be just `$FRAMEWORK_NAME`. I have a follow up which should fix it. https://github.com/Mantle/Mantle/pull/867

**Pull request merged**
