### PR TITLE
Fixed https://github.com/Mantle/Mantle/issues/626

### LINKED ISSUE #626: Xcode 7.1 compilation issue for Pods that depend on Mantle
`Mantle.h` uses angular imports which leads to this error: `Mantle.h:19:9: Include of non-modular header inside framework module 'Mantle.Mantle'` in Pods that use `Mantle` as a dependency.

I'm not sure if the suggested fix is to **NOT** use angular imports in `Mantle.h`. More information here: https://github.com/CocoaPods/CocoaPods/issues/4420

### PR DESCRIPTION
**Pull request by priteshshah1983**
Fixes #626

### CODE REVIEW

**Comment by robb** [comment]
Hmm, https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/466 looks similar and they concluded angular imports were fine and it seems fixed in CocoaPods master according to https://github.com/CocoaPods/CocoaPods/issues/4420.

Do we still need this, then?

**Comment by priteshshah1983** [comment]
AFAIK, this is only an issue when you try to use a pod that depends on Mantle. We have resorted to using a private podspec: https://github.com/magnetsystems/Specs/blob/master/Mantle/3.0.0/Mantle.podspec.json#L21 as a workaround. I will try to create a simple repro and post details.

**Comment by priteshshah1983** [comment]
@robb I created a Pod called `iMantle` here:

The podspec is here: https://github.com/priteshshah1983/iMantle/blob/master/iMantle.podspec

With the `public_header_files` line in the podspec: https://github.com/priteshshah1983/iMantle/blob/master/iMantle.podspec#L37 , I get the following error:

```
/Users/pshah/Desktop/iMantle/Pod/Classes/IMUser.h:9:9: Include of non-modular header inside framework module 'iMantle.IMUser'
```

This is offending line: `#import <Mantle/Mantle.h>` in `IMUser.h`

**Comment by priteshshah1983** [comment]
This is what fixes it: https://github.com/priteshshah1983/iMantle/commit/2b94819fdbfbce38da6e293f933dbf9d3640c8d3

The fixed project is here: https://github.com/priteshshah1983/iMantle/tree/no-angular-brackets

**Comment by robb** [comment]
Hey, I'm a little backlogged at the moment but I'm marking this help wanted /cc @Mantle/mantle

**Comment by JanGorman** [comment]
@priteshshah1983 Are you actually trying to build a Swift or Objective-C framework? It looks like you selected Swift during the `pod lib create iMantle` phase. If you run the command and select Objective-C, importing Mantle works perfectly fine (See sample here: https://github.com/JanGorman/iMantle). So it'll be some Xcode project setting generated by CocoaPods that prevents this from working properly

**Comment by mdiep** [comment]
This is 100% the wrong thing to do. This header needs to be using angle brackets for the import because it's a framework header.

**Comment by dcaunt** [comment]
I don't fully understand what's not working here, but it looks like this generally indicates a problem with header search paths. That's why the angled bracket includes don't work.

**Comment by priteshshah1983** [comment]
@mdiep Xcode's framework project template suggests using angle brackets, but there are a lot of popular open-source projects that use non-angle brackets in the framework header. AFNetworking comes to mind: https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFNetworking.h

Am I missing something?

**Comment by JanGorman** [comment]
@priteshshah1983 If you simply remove the `ReplaceMe.swift` file from your project and run `pod install` in the Example directory again your project will compile. I suggest you try that and diff the generated Xcode project files, they should then contain some hint into what CocoaPods generates differently for a Swift vs. a Objective-C pod

**Comment by mdiep** [comment]
> Xcode's framework project template suggests using angle brackets, but there are a lot of popular open-source projects that use non-angle brackets in the framework header. AFNetworking comes to mind: https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFNetworking.h
> 
> Am I missing something?

AFNetworking is widely used, but I wouldn't (and don't) trust it to do the correct thing.

`#import "header.h"` is for user headers. `#import <header.h>` is for system and framework headers. Take a look at any of Apple's frameworks: the umbrella header uses angle brackets to import the other headers.

If `#import <header.h>` doesn't work with CocoaPods, it's a CocoaPods issue.

**Comment by priteshshah1983** [comment]
> @priteshshah1983 If you simply remove the ReplaceMe.swift file from your project and run pod install in the Example directory again your project will compile. I suggest you try that and diff the generated Xcode project files, they should then contain some hint into what CocoaPods generates differently for a Swift vs. an Objective-C pod

@JanGorman Thanks for a great pointer! I will keep playing with this and report back results.

**Comment by priteshshah1983** [comment]
@mdiep Thanks for pointing out that Apple's frameworks use angle brackets, I never noticed that! And, they seem to do it consistently as well.

**Comment by priteshshah1983** [comment]
Thanks everyone for your help!

I wanted to close the loop and report my findings:

The fix for https://github.com/CocoaPods/CocoaPods/issues/4420 indeed fixes this issue. Sorry, I was under the impression that `Cocoapods v0.39.0` already included that fix, but it does not.

The complete working project with `Cocoapods v1.0.0.beta.3` can be found here: https://github.com/priteshshah1983/iMantle/tree/cocoapods-1.0.0.beta.3

I also fixed the project with `Cocoapods v0.39.0` by manually applying the following workaround:
https://github.com/priteshshah1983/iMantle/commit/f8e9cc39c4bbd3778462c52fe8bcc9d6c2ec0e72

**Comment by robb** [comment]
Thanks for chiming in y'all. :sparkling_heart:

**Pull request closed without merging**
