### PR TITLE
Allow multiple JSON fields

### PR DESCRIPTION
**Pull request by rickytribbia**
I made this change because in a project the JSON used for web services
was awful.

For example:

```
{ “image1” : “…”,
 “image2” : “…”,
 “image3” : “..”,
… }
```

So I find convenient made this change to extend Mantle support for
multiple JSON fields.
Multiple fields require a JSONTransformer with NSArray as input.

### CODE REVIEW

**Comment by robb** [comment]
I'm not sure excatly what this will do, but is it equivalent to #263?

**Comment by rickytribbia** [comment]
Yes, I think so!

2015-03-02 18:29 GMT+01:00 Robert Böhnke <notifications@github.com>:

**Comment by jspahrsummers** [comment]
In that case, this has already been implemented for Mantle 2.0. :sparkles:

**Comment by rickytribbia** [comment]
Thank you very much,
I'm glad to hear that.

And thank you for your work, it's a huge tool for our works.

Regards,


2015-03-02 18:42 GMT+01:00 Justin Spahr-Summers <notifications@github.com>:

**Pull request closed without merging**
